[application]

# App (Project) Name
name = "onerm"

# Dioxus App Default Platform
# desktop, web, mobile, ssr
default_platform = "web"

# `build` & `serve` dist path
out_dir = "dist"

[web.app]

# HTML title tag content
title = "onerm"

base_path = "onerm"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = [
  "/onerm/assets/chota.min.css"
]

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
