[application]

# App (Project) Name
name = "onerm"

# Dioxus App Default Platform
# desktop, web, mobile, ssr
default_platform = "web"

# `build` & `serve` dist path
out_dir = ""

asset_dir = "assets"

[web.app]

# HTML title tag content
title = "onerm"

base_path = "onerm"
